### ISSUE TITLE
Create mock data to insert in our database

### ISSUE THREAD

**Issue by fernandodlcruz** [fernandodlcruz/HotelReservation#13]
We need to mock the data for the first iteration for us to be able to test the first two use cases

**Comment by fernandodlcruz** [comment]
Wiki with mock data created at Mock Data Page

**Comment by fernandodlcruz** [comment]
Created data for rooms

**Comment by SAMofNAV** [comment]
I've updated the Mock Data wiki. We need to update the Phone column from the CUSTOMER table into the BIGINT data type.
