### ISSUE TITLE
Create Tables in Database.

### ISSUE THREAD

**Issue by SAMofNAV** [fernandodlcruz/HotelReservation#3]
Run the following script in our live database to generate the tables for our Hotel Reservation System.

CREATE TABLE [VENDOR] (
  [VendorID] INT NOT NULL IDENTITY,
  [Name] VARCHAR(50) NOT NULL,
  [VendorToken] VARCHAR(100) NOT NULL
  CONSTRAINT PK_VENDOR PRIMARY KEY (VendorID) 
);

CREATE TABLE [CUSTOMER] (
  [CustomerID] INT NOT NULL IDENTITY,
  [FirstName] VARCHAR(50) NOT NULL,
  [LastName] VARCHAR(50) NOT NULL,
  [Email] VARCHAR(50) NOT NULL,
  [Phone] INT NOT NULL,
  [VendorID] INT NOT NULL
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CustomerID),
  CONSTRAINT FK_CUSTOMER_VENDOR FOREIGN KEY (VendorID) 
	REFERENCES VENDOR(VendorID)
);

CREATE TABLE [ROOM] (
  [RoomNumber] INT NOT NULL,
  [Capacity] INT NOT NULL,
  [Price] MONEY NOT NULL,
  [Description] VARCHAR(200) NOT NULL
  CONSTRAINT PK_ROOM PRIMARY KEY (RoomNumber)
);

CREATE TABLE [ROOM_BOOKING] (
  [RoomNumber] INT NOT NULL,
  [CustomerID] INT NOT NULL,
  [StartDate] DATE NOT NULL,
  [EndDate] DATE NOT NULL
  CONSTRAINT PK_ROOM_BOOKING PRIMARY KEY (RoomNumber, CustomerID),
  CONSTRAINT FK_ROOM_BOOKING_ROOM FOREIGN KEY (RoomNumber) 
	REFERENCES ROOM(RoomNumber),
  CONSTRAINT FK_ROOM_BOOKING_CUSTOMER FOREIGN KEY (CustomerID) 
	REFERENCES CUSTOMER(CustomerID)
);

**Comment by fernandodlcruz** [comment]
Created the database and added Samuel and Rafael IP addresses to access it.
