### ISSUE TITLE
Get Project Running On All Machines

### ISSUE THREAD

**Issue by SAMofNAV** [fernandodlcruz/HotelReservation#5]
Our project currently only runs on Fernando's machine. We need the code running on all machines so we can all assist programming and testing of our code. We will get together to fix this issue. Failing this, iteration 0 coding will have to be done on Fernando's machine only.

**Comment by SAMofNAV** [comment]
We have managed to run the code on Fernando and Rafael's machines

**Comment by fernandodlcruz** [comment]
Rafael's computer is now working properly. It's running the project and using Git all correctly.

**Comment by fernandodlcruz** [comment]
Samuel's computer is missing a Web Server to run the project. It seems if we install Tomcat it will work properly. Waiting for Samuel to install it and run some tests.
